# -*- coding: utf-8 -*-
"""darija_solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NoVKeRMc0yx0Xmg9ETYuEOFPW3liUK17
"""

! uv pip install -U smolagents

from smolagents import OpenAIServerModel

# Load the model
model = OpenAIServerModel(
    model_id="gemini-2.0-flash",
    api_base="https://generativelanguage.googleapis.com/v1beta",
    api_key="AIzaSyCIG1ZmPhDJktAmuzuSpajmivpaMeo5nDo",
)

response = model.client.chat.completions.create(
    model=model.model_id,
    messages=[
        {
            "role": "user",
            "content": "عفاك قلب ليا على كيفاش ناخذ عقد ازديا"
        }
    ]
)

print(response.choices[0].message.content)

from smolagents import Tool
import requests

class SearchWebTool(Tool):
    name = "moroccan_darija_web_search"
    description = "كيقلب فالمواقع المغربية على الوثائق اللي كيتطلبو فالإدارات بالدارجة المغربية."
    inputs = {
        "query": {
            "type": "string",
            "description": "شنو بغيتي تقلب عليه، مثلا: 'شنو خاصني نوجد لجواز السفر المغرب'"
        }
    }
    output_type = "string"

    def forward(self, query: str) -> str:
        try:
            api_key = "59987dee629e60fa56510999efde2faecac8beee73bcab5ad1fcea0b6d1244e8"
            response = requests.get(
                "https://serpapi.com/search",
                params={
                    "q": query,
                    "hl": "ar",        # لغة الواجهة: العربية
                    "gl": "ma",        # البلد: المغرب
                    "engine": "google",
                    "api_key": api_key
                }
            )
            data = response.json()
            results = data.get("organic_results", [])[:3]
            if not results:
                return "ما لقيتش نتائج دابا، جرب تسول بطريقة أخرى."

            return "\n\n".join(f"{r['title']}\n{r['link']}" for r in results)
        except Exception as e:
            return f"خطأ فالبحث: {str(e)}"

from smolagents import ToolCallingAgent

agent = ToolCallingAgent(
    model=model,
    tools=[SearchWebTool()],
)

# Your model and agent setup (make sure it's already defined)
# agent = ToolCallingAgent(model=model, tools=[SearchWebTool()])


# You already have model and ToolCallingAgent set up

chat_history = []

def chat(user_input):
    global chat_history

    # Add user input to history
    chat_history.append(f"User: {user_input}")

    # Combine the chat history into one prompt
    conversation = "\n".join(chat_history) + "\nAssistant:"

    # Send to the agent
    result = agent.run(conversation)

    # Save assistant reply
    chat_history.append(f"Assistant: {result}")

    return result



# Usage
print(chat("شنو خاصني نوجد باش نخرج جواز السفر؟"))
print(chat("وش خاصني نجيب معايا الصور؟"))
print(chat("ومفهمتش"))

print(chat("شنو خاصني نوجد باش نجدد البيرمي ديالي"))

print(chat("شكون نتا"))

print(chat("شنو خاصني ندير باش ناخد رخصة البناء فالدوار"))

print(chat("amiiiiine"))

print(chat("lah yhfdeek"))

print(chat("شنو خاصني باش نأسس شركة فالمغرب"))

print(chat("كيفاش بلان هاد SARL"))

def detect_intent(user_input: str) -> str:
    intent_keywords = {
        "passport": ["جواز", "الباسبور", "passport"],
        "id_card": ["لاكارط", "بطاقة التعريف", "كارط ناسيونال"],
        "driver_license": ["رخصة", "السياقة", "permis"],
        "birth_certificate": ["ازدياد", "عقد", "acte de naissance"],
        "residence": ["الإقامة", "كارت الإقامة", "séjour"],
    }
    for intent, keywords in intent_keywords.items():
        if any(word in user_input.lower() for word in keywords):
            return intent
    return "unknown"

def extract_pdf_links(results: list) -> list:
    return [r['link'] for r in results if r['link'].endswith(".pdf")]

chat_history = []

def add_message(role, content):
    chat_history.append({"role": role, "content": content})

def smart_chat(user_input, tool):
    add_message("user", user_input)

    intent = detect_intent(user_input)

    if intent == "id_card":
        query = "وثائق بطاقة التعريف الوطنية المغرب"
    elif intent == "passport":
        query = "وثائق جواز السفر المغرب"
    elif intent == "driver_license":
        query = "وثائق رخصة السياقة المغرب"
    elif intent == "birth_certificate":
        query = "وثائق عقد الازدياد المغرب"
    else:
        query = user_input  # fallback

    global chat_history

    # Add user input to history
    chat_history.append(f"User: {user_input}")

    # Combine the chat history into one prompt
    conversation = "\n".join(chat_history) + "\nAssistant:"

    # Send to the agent
    result = agent.run(conversation)

    # Save assistant reply
    chat_history.append(f"Assistant: {result}")

    return result

    result = tool(query)
    add_message("assistant", result)
    return result

def smart_chat(user_input, tool):
    add_message("user", user_input)

    # تحليل بسيط للطلب
    if "لاكارط" in user_input or "بطاقة التعريف" in user_input:
        if "أول مرة" in user_input or "جديدة" in user_input:
            query = "وثائق بطاقة التعريف الوطنية لأول مرة المغرب"
        elif "تجديد" in user_input:
            query = "وثائق تجديد بطاقة التعريف الوطنية المغرب"
        else:
            return "وش أول مرة كتديرها ولا غير تجديد؟"

        result = tool(query)
        add_message("assistant", result)
        return result

    elif "جواز السفر" in user_input or "الباسبور" in user_input:
        query = "وثائق جواز السفر المغرب 2025"
        result = tool(query)
        add_message("assistant", result)
        return result

    else:
        # fallback للبحث العام
        result = tool(user_input)
        add_message("assistant", result)
        return result

tool = SearchWebTool()

print(smart_chat("بغيت نخرج لاكارط ناسيونال", tool))
print(smart_chat("أول مرة", tool))
print(smart_chat("شنو خاصني نوجد باش نخرج الباسبور", tool))

# === تجربة محادثة حقيقية ===

tool = SearchWebTool()

print("User: بغيت نعرف شنو خاصني باش نخرج جواز السفر؟")
response = smart_chat("بغيت نعرف شنو خاصني باش نخرج جواز السفر؟", tool)
print("Bot:", response)

print("\nUser: وشنو الوثائق المطلوبة للكارط الوطنية؟")
response = smart_chat("وشنو الوثائق المطلوبة للكارط الوطنية؟", tool)
print("Bot:", response)

print("\nUser: بغيت ندير رخصة السياقة، شنو الأوراق؟")
response = smart_chat("بغيت ندير رخصة السياقة، شنو الأوراق؟", tool)
print("Bot:", response)

from smolagents import Tool, ToolCallingAgent
from smolagents.models import OpenAIServerModel

class SearchWebTool(Tool):
    name = "moroccan_web_search"
    description = "Searches Moroccan web for up-to-date admin documents."
    inputs = {
        "query": {"type": "string", "description": "Search query"}
    }
    output_type = "string"

    def forward(self, query: str) -> str:
        # Here, just a mock for example:
        return f"نتائج البحث على: {query}"

def detect_intent(text):
    intents = {
        "passport": ["جواز", "باسبور"],
        "id_card": ["كارط", "بطاقة", "بطاقة التعريف"],
        "driver_license": ["رخصة", "سياقة", "رخصة السياقة"],
        "birth_certificate": ["عقد ازدياد", "شهادة ازدياد"],
        "residence": ["كارت الإقامة", "كارت إقامة", "بطاقة الإقامة"],
    }
    text_lower = text.lower()
    for intent, keywords in intents.items():
        for kw in keywords:
            if kw in text_lower:
                return intent
    return "general"

model = OpenAIServerModel(
    model_id="gemini-2.0-flash",
    api_base="https://generativelanguage.googleapis.com/v1beta",
    api_key="AIzaSyCIG1ZmPhDJktAmuzuSpajmivpaMeo5nDo",
)

agent = ToolCallingAgent(
    model=model,
    tools=[SearchWebTool()]
)

chat_history = []

def chat(user_input):
    global chat_history

    intent = detect_intent(user_input)

    # Map intent to Moroccan doc search query
    queries = {
        "passport": "وثائق استخراج جواز السفر المغرب 2025",
        "id_card": "وثائق استخراج بطاقة التعريف الوطنية المغرب 2025",
        "driver_license": "وثائق استخراج رخصة السياقة المغرب 2025",
        "birth_certificate": "وثائق استخراج عقد الازدياد المغرب 2025",
        "residence": "وثائق استخراج بطاقة الإقامة المغرب 2025",
        "general": user_input
    }
    query = queries.get(intent, user_input)

    chat_history.append(f"User: {user_input}")
    prompt = "\n".join(chat_history) + f"\nAssistant:"

    # The agent expects the entire conversation prompt to decide on tools usage
    response = agent.run(prompt)

    chat_history.append(f"Assistant: {response}")

    return response


# Example conversation in Moroccan Darija:
print(chat("شنو خاصني نوجد باش نخرج جواز السفر؟"))
print(chat("وش خاصني نجيب معايا الصور؟"))
print(chat("ومفهمتش"))